name: Build and Push Docker Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Read version from gradle.properties
        id: get_version
        run: |
          echo "VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV
      - name: Build the project
        run: ./gradlew shadowJar
      - name: Build Docker image
        run: |
          docker build -t mamaliang/npps:${{ env.VERSION }} .
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: |
          docker push mamaliang/npps:${{ env.VERSION }}
